### ISSUE TITLE
is this ready ?

### ISSUE THREAD

**Issue by gedw99** [rimusz/coreos-osx-gui#10]
sorry to be so blunt. But i working with a large team and we are transitioning to CoreOS, and this tool will be great. We would be happy to give feedback and help fix bugs too.

But just want to know if this is usable yet ?

**Comment by rimusz** [comment]
@gedw99 any feedback, any bug fixes and PRs are welcome.
I made it just for myself for the start, now we are using it with my small team at my work too.
As you can see I add new things every week and fixes too.

There are two cluster based Apps as well, those might be useful for you guys too.
:-)

**Comment by gedw99** [comment]
I have boot2docker, virtual box installed.
then i installed coreOS GUI

i get this error
Last login: Tue Mar 10 16:50:56 on ttys000
gerards-MacBook-Air:~ gerardwebb$ /Users/gerardwebb/Desktop/CoreOS\ GUI.app/Contents/Resources/vagrant_destroy.command; exit;
Vagrant failed to initialize at a very early stage:

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /Users/gerardwebb/coreos-osx/coreos-vagrant/Vagrantfile
Message: undefined method `require_version' for Vagrant:Module
Press [Enter] key to continue...

**Comment by rimusz** [comment]
Boot2docker does not interfere with my App. :)
Also you need iTerm2 installed.

Have you done the full install via Setup / Initial setup of CoreOS VM?
As that gets CoreOS Vagrant files from github and installs CoreOS VM

**Comment by gedw99** [comment]
I forgot i did not have vagrant :)  - everything now works.

i had to run the updates in order to get the UI running.

Very Nice ...

Now i am curious what you meant by "There are two cluster based Apps as well" ??

**Comment by rimusz** [comment]
To bootstrap  small CoreOS cluster on your Mac - https://github.com/rimusz/coreos-osx-gui-cluster
and CoreOS cluster with Kubernetes - https://github.com/rimusz/coreos-osx-gui-kubernetes-cluster

**Comment by gedw99** [comment]
the Core OS cluster with Kubernetes installed easily. needed to run an upgrade also to get it all going.
So, this one has no docker UI - i assume because we are running MANY virtual boxes instance to represent real servers. Hence each one can be considered a pod ?

We have been using ansible allot. Now i need to work out how to integrate the Kafka and Cassandra images.

thanls for your help

**Comment by rimusz** [comment]
Yes, for the cluster dockerUI does not make sense to have.

**Comment by gedw99** [comment]
yes thanks. its works well
