### ISSUE TITLE
Won't open application on Mac OS X 10.10.3

### ISSUE THREAD

**Issue by yakovkhalinsky** [rimusz/coreos-osx-gui#7]
After moving the app into my `Applications` folder and double clicking on it I get the following message

![image](https://cloud.githubusercontent.com/assets/646086/6135373/338aa052-b1bc-11e4-81cd-ae7fba0d82f9.png)

**Comment by rimusz** [comment]
@yakovkhalinsky I'm seeing this time by time too, even it is happening with the dmg file uploaded to github. Sharing the same zip/dmg file via e.g dropbox everything is fine. It looks like github damages it.
I'm looking for the solution

**Comment by yakovkhalinsky** [comment]
thanks :+1: haven't used this app for a while and I'm keen to try it again :smile:

**Comment by rimusz** [comment]
I will try to find why it is happening, as at least with OS X 10.10/10.10.1 for sure was fine.
I'm using it myself a lot, so I add new bits time by time.

**Comment by rimusz** [comment]
I think I found a problem, I was sharing a code via Google drive (moved my projects to it recently).
I copied the source folder to my Desktop and built the binary there, now it looks OK, I can download and run on my Macs at no problem. Let me know how it goes for you. Thanks

**Comment by yakovkhalinsky** [comment]
Tried downloading the release DMG again.

Now when I open it I never see the list of files inside the mounted image :crying_cat_face: 
![image](https://cloud.githubusercontent.com/assets/646086/6137651/acbc6034-b1ce-11e4-86f5-ee2f52106e1a.png)

**Comment by yakovkhalinsky** [comment]
Sorry false alarm, downloaded latest released and the image mounts fine and the app runs :+1:

**Comment by rimusz** [comment]
cool, so we can close this one
